<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Password reset link was sent to your email</name>
   <tag></tag>
   <elementGuidId>22f66166-f856-4ce3-825f-51d7fd344a67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='alert-dialog-description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alert-dialog-description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Password reset link was sent to your email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4513ddec-cbb0-40b6-a5c1-ce70718fc512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiDialogContentText-root MuiTypography-body1 MuiDialogContentText-root css-o3d33y</value>
      <webElementGuid>b493a049-7ba4-462e-bfb4-835a547ab53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-dialog-description</value>
      <webElementGuid>6cfd7229-b697-41c0-b8df-053bd47fefe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password reset link was sent to your email</value>
      <webElementGuid>a4b48b8a-b596-4d6e-b956-26082efa7261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-dialog-description&quot;)</value>
      <webElementGuid>7b0cd240-6af0-4c28-ade2-d00b2ec8a600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='alert-dialog-description']</value>
      <webElementGuid>e4a1a1c0-0daf-4757-add7-919329c5e79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is an example of a forgot password form for test automation practice.Email: test@test.com'])[1]/following::p[1]</value>
      <webElementGuid>9386bc12-6a48-4692-8075-f8fd82879dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::p[1]</value>
      <webElementGuid>62cf09a4-6aa3-4fb2-beba-55408ab477ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password reset link was sent to your email']/parent::*</value>
      <webElementGuid>4bffa313-caef-472a-aa5e-2116f5437d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/p</value>
      <webElementGuid>5806bd2e-1931-4515-9712-c0d8261877ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'alert-dialog-description' and (text() = 'Password reset link was sent to your email' or . = 'Password reset link was sent to your email')]</value>
      <webElementGuid>435a956e-c4bc-44a0-bc04-2e4e296606c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
