<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login Alert Dialog</name>
   <tag></tag>
   <elementGuidId>8c8d8332-2f04-40bf-a173-a86e929dfe5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>https://automagic-test-app.netlify.app/</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alert-dialog-title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
